openapi: 3.0.2
info:
  title: studentManager API
  version: "1.0"
servers:
  - url: https://virtserver.swaggerhub.com/TsantaniainakyleRAKOTOARISON/studentmanager/1.0
    description: SwaggerHub API Auto Mocking
  - url: https://api.server.test/v1
paths:
  /groups:
    get:
      parameters:
        - name: groupName
          in: query
          description: sort by groupName
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: groupYear
          in: query
          description: sort by groupYear
          required: false
          style: form
          explode: true
          schema:
            type: string
      responses:
        "200":
          description: OK
    put:
      responses:
        "200":
          description: OK
    post:
      requestBody:
        content:
          /application/json:
            schema:
              $ref: '#/components/schemas/group'
      responses:
        "200":
          description: ok
    delete:
      parameters:
        - name: id
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
      responses:
        "200":
          description: deleted
  /students:
    get:
      operationId: getStudents
      parameters:
        - in : query
          name: studentName
          description: sort by studentName
          schema:
            type: string
      responses:
        '200':
          description: OK
    put:
      responses:
        '200':
          description: OK
    delete:
      parameters:
        - in : query
          name: id
          schema:
            type: string
      responses:
        '200':
          description: deleted
    post:
      requestBody:
        content:
          /application/json:
            schema:
              $ref: "#/components/schemas/student"
      responses:
        '200':
          description: ok

components:
  schemas:
    group:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        year:
          type: string
          format: date
        studentNumber:
          type: number
    student:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        sex:
          type: string
          enum:
            - Male
            - Female
        birthdate:
          type: string
          format: date
        reference:
          type: string
        group:
          type: string
